### ISSUE TITLE
I completed the lab for this section, but for some reason, it's not registering the fact that I opened a pull request...

### ISSUE THREAD

**Issue by coltonstaab1** [learn-co-curriculum/CSS-Styling#1]

**Comment by AnnJohn** [comment]
Hi @coltonstaab1 this looks like its a technical problem, so could you please file a bug report (if you hover over your profile pic in Learn you'll see an option to Report a Bug). Also you can use the Ask a Question tool in Learn and someone from our support team will help you out! Thanks
