### ISSUE TITLE
broken links?

### ISSUE THREAD

**Issue by ryanmanchester** [learn-co-curriculum/CSS-Styling#14]
After completing the code along, the CSS would not read. I talked with a Tech Coach and he couldn't figure it out either, so I'm flagging it to get it looked at. Thank you!

**Comment by maxwellbenton** [comment]
Hi there @ryanmanchester ,

I took a peek at your repository.  In your `<head>` section you have a typo in your `<link rel="stylesheet" href"css/style.css">` - missing the `=` after `href`, which is what is causing your CSS not to load.

I am going to close this issue for now, but if you feel this does not resolve the issue you had, please feel free to open a new issue and we can take a look.

As always, thanks for contributing! 💙
