### ISSUE TITLE
Coding Directory Confusion

### ISSUE THREAD

**Issue by nicolefederici** [learn-co-curriculum/CSS-Styling#2]
Hi. I just spoke with Randall. He was great, btw! I've been having problems with pushing for days now.. and the solution was that I should NOT follow the tutor in the video. At the beginning of the video, for a second, a little white box pops up to tell you to stay in the cloned copy of the lesson. I missed this, and tried to cd all over the place. This caused problems when pushing to Git Hub. I ended up doing several hours of merge conflict resolution as a result the other day, and still didn't know where I was supposed to cd into... Now I know. It would be helpful if there was a note on the webpage itself saying "stay where you are! don't cd into wherever the guy tells you to!" Also- practice creating a branch to learn how to merge it to the master - just for good practice. And here is how... As a beginner, this would be a lot clearer and more helpful. I was at sea for about a week because I didn't know where I was supposed to code. It caused me to be anxious that my work would be lost or recorded improperly. Thanks so much. Kate was a big help too, by the way.

**Comment by pletcher** [comment]
Thanks for reporting this! We'll revisit the video ASAP and be sure to clarify the instructions.

**Comment by jongrover** [comment]
Added additional clarification in README.
