### ISSUE TITLE
Getting an error when running 'learn' command

### ISSUE THREAD

**Issue by joelbitar1986** [learn-co-curriculum/CSS-Styling#4]
![screenshot from 2016-03-21 18 39 18](https://cloud.githubusercontent.com/assets/17229217/13936461/3f6d2b30-ef94-11e5-911a-ab6a38b307d0.png)

When running learn command, presented with a strange issue. 'Please install selenium standalone server'

**Comment by joelbitart1986** [comment]
It seems like other Linux users are facing this issue, not sure if Windows and Mac users are dealing with it.

**Comment by pletcher** [comment]
`chmod 0600 ~/.netrc` should fix it. (Use `sudo` if you need to.) This is indeed a Linux setup thing.
