### ISSUE TITLE
Local build failing

### ISSUE THREAD

**Issue by LSleutsky** [learn-co-curriculum/CSS-Styling#5]
The local build is failing with some outrageous error messages, which makes no sense since this is a simple code along. I cannot get past this very simple lab

**Comment by pletcher** [comment]
Thanks for reporting this issue. If you were running the lab in a non-*nix environment (Windows, Nitrous), you might have run into some issues that were addressed in https://github.com/learn-co-curriculum/CSS-Styling/commit/2e667d0b6384ce2579315f6f9ade5bb645cbe407.

Let us know if you still see errors. (Please paste the full stack trace for the error into the issue.)
