### ISSUE TITLE
Green_onion Issues

### ISSUE THREAD

**Issue by snsavage** [learn-co-curriculum/CSS-Styling#6]
This lab is still using the green_onion gem which has an issue with the rainbow gem that it requires.  I had problems with this gem a few days ago when working on the HTML labs and I thought that it had been removed from the labs?  I see that other people have successfully submitted pull requests in the last few days.  I'm assuming that they are successfully using the gem?  I was able to get my tests to pass only by modifying my local version of the green_onion gem to work properly with rainbow.

**Comment by snsavage** [comment]
If green_onion is going to continue to be used can we just create a Learn specific fork, fix the rainbow require issue and then use that version in the labs?

**Comment by AnnJohn** [comment]
thanks @snsavage for raising this.

cc'ing @pletcher. can you look into this as it might be still an issue for LV students? thanks

**Comment by pletcher** [comment]
Fixed. https://github.com/learn-co-curriculum/CSS-Styling/commit/2e667d0b6384ce2579315f6f9ade5bb645cbe407
