### ISSUE TITLE
Not showing as complete

### ISSUE THREAD

**Issue by LSleutsky** [learn-co-curriculum/CSS-Styling#7]
This lesson, even though it is complete and finished, properly, does not show up as finished under my profile. It says that I have completed 65/66 lessons in the HTML / CSS section, but I have completed and passed them all, but this lab is still being buggy - before the tests would not run and pass due to an error on the back-end, and then when that was fixed and the tests passed, it still shows as incomplete, even though when I go to the lab, it is marked as forked, submitted & passed, and finished.

Will this be fixed?

**Comment by AnnJohn** [comment]
hi @LSleutsky this is a technical bug so could you file a bug report for this. If you hover over your profile pic in Learn, you'll see an option to file a report. 

Thanks!

**Comment by LSleutsky** [comment]
Gotcha, thanks. Left a bug report. Hopefully they will address it...
