### ISSUE TITLE
Still showing as an incomplete lab

### ISSUE THREAD

**Issue by LSleutsky** [learn-co-curriculum/CSS-Styling#8]
I have raised a couple issues, as well as filed a couple bug reports, but this lab is still showing as incomplete. I would like to see all the completed lessons of mine show up as complete, as it serves as extra motivation for me to see it fully done, so I can push forward in completing more and more, but it continues to be bugged out and show as not completed, even though it has been run, tested, and complete. It has been like this for a couple weeks now, and I am wondering if this will be remedied by the Learn team? I hope so, cause it is definitely important to have the HTML & CSS section showing as fully complete, instead of missing 1 facet, which it currently does. It says 65/66 instead of 66/66. Hopefully this will be fixed. Thank you!

**Comment by AnnJohn** [comment]
hi @LSleutsky sorry for the continued issue with this. We're working on making this accurate, but in the meantime you can also try emailing support@learn.co and that might be helpful. thanks!
